server:
  port: 7071
  servlet:
    context-path: /

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: mall-coupon

coupon:
  user:
    name: zhangsan
    age: 22