server:
  port: 8090
spring:
  redis:
    # Redis服务器地址
    host: 121.196.210.187
    # Redis服务器连接端口
    port: 16379
    # 密码
    password: redis123
    # Redis数据库索引
    database: 0
    # Redis服务器连接密码(默认为空)
    #password:
    timeout: 5000
    # Redis服务器连接池
    jedis:
      pool:
        max-active: 100 # 连接池最大连接数（负值表示没有限制）
        max-wait: 3000 # 连接池最大阻塞等待时间（负值表示没有限制）
        max-idle: 200 # 连接池最大空闭连接数
        min-idle: 50 # 连接汉最小空闲连接数
